### ISSUE TITLE
Integration issue zoho apptics with react native in ios

### ISSUE THREAD

**Issue by adilkhanWalee** [zoho/Apptics#4]
i am facing an issue during integration with react native ios
#import "Apptics/Apptics.h".      'Apptics/Apptics.h' file not found
Expected expression
as i already install sdk by this command but still app delegate m file show expected expression in [Apptics initializeWithVerbose:(BOOL)];
line
i want a live chat module in our react native app
it is working in android but i am facing above mentioned issue in ios
as i already install apptics with this command.
npm install @zoho_apptics/apptics-react-native

**Comment by xtyuo04** [comment]
Hey Adil,

We request you to please follow the steps mentioned under iOS in the below doc.
https://www.zoho.com/apptics/resources/SDK/react_native/integration.html

Also, you do not have to import Apptics in their AppDelegate class file.

Hope this helps!

**Comment by adilkhanWalee** [comment]
when i fellow this documentation then my app is crashing when i import
import { Apptics } from ***@***.***_apptics/apptics-react-native';


and error is this
Exception NSException * "-[_UITextLayoutCanvasView contentViewInvalidated]:
unrecognized selector sent to instance 0x151cf9080" 0x0000000283656040
name __NSCFConstantString * "NSInvalidArgumentException" 0x00000001fbb2a1b0
reason __NSCFString * "-[_UITextLayoutCanvasView contentViewInvalidated]:
unrecognized selector sent to instance 0x151cf9080" 0x000000028162fb80
userInfo void * NULL 0x0000000000000000
reserved __NSDictionaryM * 2 key/value pairs 0x00000002838dbce0
argc int 1
argv char ** 0x16dc67800 0x000000016dc67800
Adil Khan
Senior React Native Developer

**Comment by adilkhanWalee** [comment]
and please also explain where should i place this code
Build script usage:

run --upload-symbols-for-configurations="Release, Appstore"
--config-file-path="YOUR_PATH/apptics-config.plist"
--app-group-identifier="group.com.company.application [Optional]"

   - --config-file-path pass your config file path if it is not added to
   your project root.
   - --app-group-identifier if you have enabled app group identifier for
   your app's target.
   - --upload-symbols-for-configurations string, an optional parameter to
   pass your configuration name debug, release, or add a custom name with
   comma-separated for which the dSYMs will be uploaded without any prompt
   during App Store submission process via CI, CT, and CD.

Adil Khan
Senior React Native Developer

**Comment by xtyuo04** [comment]
and error is this
Exception NSException * "-[_UITextLayoutCanvasView contentViewInvalidated]:
unrecognized selector sent to instance 0x151cf9080" 0x0000000283656040
name __NSCFConstantString * "NSInvalidArgumentException" 0x00000001fbb2a1b0
reason __NSCFString * "-[_UITextLayoutCanvasView contentViewInvalidated]:
unrecognized selector sent to instance 0x151cf9080" 0x000000028162fb80
userInfo void * NULL 0x0000000000000000
reserved __NSDictionaryM * 2 key/value pairs 0x00000002838dbce0
argc int 1
argv char ** 0x16dc67800 0x000000016dc67800

Could you please share the full crash log for this?

**Comment by xtyuo04** [comment]
and please also explain where should i place this code
Build script usage:

run --upload-symbols-for-configurations="Release, Appstore"
--config-file-path="YOUR_PATH/apptics-config.plist"
--app-group-identifier="group.com.company.application [Optional]"

   - --config-file-path pass your config file path if it is not added to
   your project root.
   - --app-group-identifier if you have enabled app group identifier for
   your app's target.
   - --upload-symbols-for-configurations string, an optional parameter to
   pass your configuration name debug, release, or add a custom name with
   comma-separated for which the dSYMs will be uploaded without any prompt
   during App Store submission process via CI, CT, and CD.

Could you please let me know if you have downloaded and added the apptics-config file and run script to the build phases of Xcode project?

**Comment by adilkhanWalee** [comment]
Thanks zoho team i integrated zoho Saleiq chat in our react native app
successfully
Adil Khan
Senior React Native Developer

**Comment by adilkhanWalee** [comment]
As i was importing #import "Apptics/Apptics.h" this in delegate M file. that is not needed in react native case. 
so my issue has been fixed.
Thanks

**Comment by xtyuo04** [comment]
Happy to hear that @adilkhanWalee ..
